--
-- File generated with SQLiteStudio v3.1.1 on pon. nov 13 10:31:06 2017
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: izvajalci
CREATE TABLE izvajalci (
                idpredmeta integer REFERENCES predmeti(id),
                iducitelja integer REFERENCES ucitelji(id),
                vloga integer REFERENCES ucitelji(id),
                PRIMARY KEY (idpredmeta, iducitelja, vloga)
                );

-- Table: predmeti
CREATE TABLE predmeti (
                 id integer PRIMARY KEY, --AUTOINCREMENT --NE RABIMO
                 ime text,
                 ects integer               
                 );
INSERT INTO predmeti (id, ime, ects) VALUES (1, 'Afina in projektivna geometrija', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (2, 'Aktuarska matematika', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (3, 'Algebra 1', 14);
INSERT INTO predmeti (id, ime, ects) VALUES (4, 'Algebra 1 (FiM)', 14);
INSERT INTO predmeti (id, ime, ects) VALUES (5, 'Algebra 2', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (6, 'Algebra 3', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (7, 'Algebraièna topologija 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (8, 'Algebraiène krivulje', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (9, 'Algebra in diskretna matematika', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (10, 'Algoritmi in podatkovne strukture 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (11, 'Algoritmi in podatkovne strukture 2', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (12, 'Analitièna mehanika', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (13, 'Analiza 1 (FiM)', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (14, 'Analiza 1 (IŠRM)', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (15, 'Analiza 1', 18);
INSERT INTO predmeti (id, ime, ects) VALUES (16, 'Analiza 2', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (17, 'Analiza 2a', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (18, 'Analiza 2b', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (19, 'Analiza 3 (IŠRM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (20, 'Analiza 3', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (21, 'Analiza 3 (FiM)', 9);
INSERT INTO predmeti (id, ime, ects) VALUES (22, 'Analiza 4', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (23, 'Analiza podatkov s programom R', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (24, 'Angleški jezik nivo A', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (25, 'Angleški jezik nivo B', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (26, 'Angleški jezik nivo C', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (27, 'Arhitektura raèunalniških sistemov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (28, 'Astronomija', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (29, 'Brezžièna in mobilna omrežja', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (30, 'Davki in davèna harmonizacija v EU', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (31, 'Davki in poslovanje podjetij', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (32, 'Denar in finance', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (33, 'Didaktika 1', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (34, 'Didaktika matematike 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (35, 'Didaktika matematike 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (36, 'Diferencialna geometrija', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (37, 'Diferencialne enaèbe', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (38, 'Digitalno naèrtovanje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (39, 'Dinamièno modeliranje (I1)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (40, 'Diskretna matematika 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (41, 'Diskretna matematika 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (42, 'Diskretne strukture 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (43, 'Diskretne strukture 2', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (44, 'Diskretno modeliranje (I1)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (45, 'Ekonometrija 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (46, 'Ekonometrija 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (47, 'Ekonomske politike EU', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (48, 'Elektronsko poslovanje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (49, 'Elementarna geometrija', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (50, 'Elementarna teorija števil', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (51, 'Evropski monetarni sistem', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (52, 'Finanèna analiza 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (53, 'Finanèna analiza 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (54, 'Finanèna ekonomija', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (55, 'Finanèna matematika 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (56, 'Finanèna matematika 2', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (57, 'Finanèna matematika 3', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (58, 'Finanèni praktikum', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (59, 'Fizika 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (60, 'Fizika 2 (FMT)', 19);
INSERT INTO predmeti (id, ime, ects) VALUES (61, 'Fizika 2', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (62, 'Fizikalni praktikum', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (63, 'Inteligentni sistemi', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (64, 'Izbrana poglavja iz diskretne matematike 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (65, 'Izbrana poglavja iz fizike', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (66, 'Izbrana poglavja iz matematike', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (67, 'Izbrana poglavja iz praktiène matematike', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (68, 'Izbrana poglavja iz raèunalniške matematike (raèunska geometrija)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (69, 'Izbrana poglavja iz raèunalniške matematike (simbolno raèunanje)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (70, 'Izbrana poglavja iz raèunalništva in informatike (Analiza omrežij)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (71, 'Izbrana poglavja iz teorije iger', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (72, 'Izbrane teme iz analize podatkov', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (73, 'Izraèunljivost in raèunska zahtevnost', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (74, 'Javne finance', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (75, 'Javne finance 2', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (76, 'Kombinatorika', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (77, 'Komuniciranje v matematiki', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (78, 'Komunikacijski protokoli', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (79, 'Kvantitativne vedenjske finance', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (80, 'Linearna algebra (IŠRM)', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (81, 'Linearna algebra (PrM)', 13);
INSERT INTO predmeti (id, ime, ects) VALUES (82, 'Logika in množice', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (83, 'Makroekonomija', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (84, 'Makroekonomija 3', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (85, 'Management finanènih institucij 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (86, 'Matematièna orodja v fiziki', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (87, 'Matematièni modeli v biologiji', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (88, 'Matematièni seminar', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (89, 'Matematièno izražanje v angleškem jeziku', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (90, 'Matematièno modeliranje', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (91, 'Matematièno modeliranje (I1)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (92, 'Matematika 1', 17);
INSERT INTO predmeti (id, ime, ects) VALUES (93, 'Matematika 1 (Fiz)', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (94, 'Matematika 2', 13);
INSERT INTO predmeti (id, ime, ects) VALUES (95, 'Matematika 2 (Fiz)', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (96, 'Matematika 2 (FMT)', 16);
INSERT INTO predmeti (id, ime, ects) VALUES (97, 'Matematika v praksi', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (98, 'Matematika z raèunalnikom', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (99, 'Mednarodna trgovinska politika', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (100, 'Mednarodne finance', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (101, 'Mednarodne finance 2', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (102, 'Mednarodno finanèno okolje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (103, 'Mehanika', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (104, 'Mehanika 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (105, 'Mikroekonomija', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (106, 'Mikroekonomija 3', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (107, 'Modeliranje in upravljanje sistemov (I1)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (108, 'Modeliranje raèunalniških omrežij', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (109, 'Modeli vrednotenja naložb', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (110, 'Monetarna ekonomija', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (111, 'Monetarna ekonomija 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (112, 'Multimedijski sistemi', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (113, 'Multivariatna analiza', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (114, 'Napredni pristopi v programskem okolju R', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (115, 'Nekomutativna algebra', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (116, 'Numerièna integracija in navadne diferencialne enaèbe', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (117, 'Numeriène metode', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (118, 'Numeriène metode 1 (FiM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (119, 'Numeriène metode 1 (PrM)', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (120, 'Numeriène metode 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (121, 'Numeriène metode za linearne sisteme upravljanja', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (122, 'Obvladovanje tveganj', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (123, 'Operacijske raziskave (2. letnik)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (124, 'Operacijske raziskave (3. letnik)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (125, 'Optimizacija', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (126, 'Optimizacija v financah', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (127, 'Optimizacijske metode (FiM)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (128, 'Optimizacijske metode (IŠRM)', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (129, 'Organizacija in management', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (130, 'Organizacija in struktura trga', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (131, 'Osnove digitalnih vezij', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (132, 'Osnove oblikovanja', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (133, 'Osnove podatkovnih baz (FiM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (134, 'Osnove podatkovnih baz (IŠRM)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (135, 'Osnove umetne inteligence', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (136, 'Parcialne diferencialne enaèbe (PrM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (137, 'Parcialne diferencialne enaèbe', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (138, 'Pedagogika z andragogiko', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (139, 'Planiranje in upravljanje informatike', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (140, 'Podatkovne baze 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (141, 'Podatkovne baze 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (142, 'Podatkovne strukture in algoritmi 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (143, 'Podatkovne strukture in algoritmi 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (144, 'Porazdeljeni sistemi', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (145, 'Poslovne finance 1', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (146, 'Poslovne finance 2', 8);
INSERT INTO predmeti (id, ime, ects) VALUES (147, 'Posplošeni linearni modeli', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (148, 'Postopki razvoja programske opreme', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (149, 'Praktièno usposabljanje', 15);
INSERT INTO predmeti (id, ime, ects) VALUES (150, 'Prevajalniki', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (151, 'Principi programskih jezikov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (152, 'Programiranje 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (153, 'Programiranje 1 (IŠRM)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (154, 'Programiranje 1 (PrM)', 9);
INSERT INTO predmeti (id, ime, ects) VALUES (155, 'Programiranje 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (156, 'Programiranje 2 (IŠRM)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (157, 'Programiranje 3', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (158, 'Programiranje specifiènih platform', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (159, 'Programska oprema pri pouku', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (160, 'Proseminar', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (161, 'Proseminar A', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (162, 'Proseminar B', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (163, 'Raèunalniška grafika in tehnologija iger', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (164, 'Raèunalniška orodja v matematiki', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (165, 'Raèunalniške komunikacije', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (166, 'Raèunalniški praktikum (PrM)', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (167, 'Raèunalniški praktikum (FiM)', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (168, 'Raèunalniški praktikum (Fiz)', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (169, 'Raèunalniški praktikum (FMT)', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (170, 'Raèunalniški praktikum', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (171, 'Raèunalniško podprto (geometrijsko) oblikovanje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (172, 'Raèunalništvo 1', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (173, 'Raèunalništvo 2', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (174, 'Raèunalništvo v praksi 1', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (175, 'Raèunalništvo v praksi 2', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (176, 'Raèunska zahtevnost in hevristièno programiranje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (177, 'Raèunsko zahtevne metode', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (178, 'Razvoj informacijskih sistemov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (179, 'Razvoj inteligentnih sistemov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (180, 'Seminar', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (181, 'Seminar 1 (skupaj)', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (182, 'Seminar 2 (skupaj)', 3);
INSERT INTO predmeti (id, ime, ects) VALUES (183, 'Simbolno raèunanje in dinamièna geometrija', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (184, 'Sistemska programska oprema', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (185, 'Sluèajni procesi 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (186, 'Spletno programiranje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (187, 'Splošna topologija', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (188, 'Statistièno obvladovanje procesov', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (189, 'Statistika', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (190, 'Statistika 1', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (191, 'Statistika v šoli', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (192, 'Tehnologija upravljanja podatkov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (193, 'Temelji finanènega in poslovodnega raèunovodstva', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (194, 'Teorija grafov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (195, 'Teorija iger', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (196, 'Teorija informacij in pogodb v financah in zavarovalništvu', 7);
INSERT INTO predmeti (id, ime, ects) VALUES (197, 'Teorija izraèunljivosti', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (198, 'Teorija kodiranja in kriptografija', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (199, 'Umetno zaznavanje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (200, 'Uvod v algebraièno geometrijo', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (201, 'Uvod v diferencialno geometrijo', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (202, 'Uvod v fiziko', 4);
INSERT INTO predmeti (id, ime, ects) VALUES (203, 'Uvod v funkcionalno analizo', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (204, 'Uvod v geometrijsko topologijo', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (205, 'Uvod v numeriène metode', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (206, 'Uvod v odkrivanje znanj iz podatkov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (207, 'Uvod v programiranje (FiM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (208, 'Uvod v programiranje', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (209, 'Verjetnost', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (210, 'Verjetnost (PrM)', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (211, 'Verjetnost 1', 5);
INSERT INTO predmeti (id, ime, ects) VALUES (212, 'Verjetnost 2', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (213, 'Verjetnost in statistika', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (214, 'Verjetnostni raèun in statistika', 10);
INSERT INTO predmeti (id, ime, ects) VALUES (215, 'Zanesljivost in zmogljivost raèunalniških sistemov', 6);
INSERT INTO predmeti (id, ime, ects) VALUES (216, 'Zgodovina matematike', 5);

-- Table: ucitelji
CREATE TABLE ucitelji (
                 id integer PRIMARY KEY,
                 ime text,
                 priimek text,
                 email text                 
                 , kabinet text);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2476, 'Daniel', 'Svenšek', 'daniel.svensek@fmf.uni-lj.si', 'F413');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2854, 'Matija', 'Lokar', 'matija.lokar@fmf.uni-lj.si', 'M506');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2890, 'Denis', 'Arèon', 'denis.arcon@fmf.uni-lj.si', 'F424');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2909, 'Vladimir', 'Batagelj', 'vladimir.batagelj@fmf.uni-lj.si', 'M406');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2912, 'Andrej', 'Bauer', 'andrej.bauer@fmf.uni-lj.si', 'M435');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2921, 'Janez', 'Bernik', 'janez.bernik@fmf.uni-lj.si', 'M502');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2927, 'Drago', 'Bokal', 'drago.bokal@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2930, 'Janez', 'Bonèa', 'janez.bonca@fmf.uni-lj.si', 'F402');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2936, 'Anita', 'Buckley', 'anita.buckley@fmf.uni-lj.si', 'M507');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2939, 'Sergio', 'Cabello', 'sergio.cabello "AT" fmf.uni-lj.si', 'M411');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2942, 'Gregor', 'Cigler', 'gregor.cigler@fmf.uni-lj.si', 'M508');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2945, 'Jakob', 'Cimpriè', 'jaka.cimpric@fmf.uni-lj.si', 'M421');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2951, 'Dean', 'Cvetko', 'dean.cvetko@fmf.uni-lj.si', 'F416, F008');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2954, 'Karin', 'Cvetko Vah', 'karin.cvetko@fmf.uni-lj.si', 'M503');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2957, 'Andrej', 'Èadež', 'andrej.cadez@fmf.uni-lj.si', 'F213');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2965, 'Miran', 'Èerne', 'miran.cerne@fmf.uni-lj.si', 'M429');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2968, 'Martin', 'Èopiè', 'martin.copic@fmf.uni-lj.si', 'F106');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2983, 'Mirko', 'Dobovišek', 'mirko.dobovisek@fmf.uni-lj.si', 'M520');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2989, 'Janez', 'Dolinšek', 'janez.dolinsek@fmf.uni-lj.si', 'F428');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2995, 'David', 'Dolžan', 'david.dolzan@fmf.uni-lj.si', 'M503');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (2998, 'Oliver', 'Dragièeviæ', 'oliver.dragicevic@fmf.uni-lj.si', 'M516');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3001, 'Irena', 'Drevenšek Olenik', 'irena.drevensek@fmf.uni-lj.si', 'F421');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3007, 'Barbara', 'Drinovec Drnovšek', 'barbara.drinovec@fmf.uni-lj.si', 'M425');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3028, 'Roman', 'Drnovšek', 'roman.drnovsek@fmf.uni-lj.si', 'M402');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3031, 'Svjetlana', 'Fajfer', 'svjetlana.fajfer@fmf.uni-lj.si', 'F427');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3037, 'Franc', 'Forstneriè', 'franc.forstneric@fmf.uni-lj.si', 'M424');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3045, 'Josip', 'Globevnik', 'josip.globevnik@fmf.uni-lj.si', 'F305');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3048, 'Boštjan', 'Golob', 'bostjan.golob@fmf.uni-lj.si', 'F416');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3060, 'Darja', 'Govekar-Leban', 'darja.govekar@fmf.uni-lj.si', 'M519');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3063, 'Milan', 'Hladnik', 'milan.hladnik@fmf.uni-lj.si', 'F320');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3069, 'Martin', 'Horvat', 'martin.horvat@fmf.uni-lj.si', 'F418');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3087, 'Gašper', 'Jakliè', 'gasper.jaklic@fmf.uni-lj.si', 'M515');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3103, 'Marjan', 'Jerman', 'marjan.jerman@fmf.uni-lj.si', 'M502');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3109, 'Martin', 'Jesenko', 'martin.jesenko@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3118, 'Martin', 'Juvan', 'martin.juvan@fmf.uni-lj.si', 'M411');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3121, 'Jure', 'Kališnik', 'jure.kalisnik@fmf.uni-lj.si', 'F310, M514');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3127, 'Borut Paul', 'Kerševan', 'borut.kersevan@ijs.si', 'F430');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3142, 'Damjan', 'Kobal', 'damjan.kobal@fmf.uni-lj.si', 'MP28 (pritlièje)');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3145, 'Pino', 'Koc', 'pino.koc@fmf.uni-lj.si', 'MP25 (pritlièje)');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3151, 'Alojzij Franc', 'Kodre', 'alojz.kodre@fmf.uni-lj.si', 'F401');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3169, 'Tomaž', 'Košir', 'tomaz.kosir@fmf.uni-lj.si', 'M4.31');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3172, 'Jernej', 'Kozak', 'jernej.kozak@fmf.uni-lj.si', 'M407');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3175, 'Marjetka', 'Krajnc', 'marjetka.krajnc@fmf.uni-lj.si', 'M515');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3178, 'Edvard', 'Kramar', 'edvard.kramar@fmf.uni-lj.si', 'M428');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3184, 'Peter', 'Križan', 'peter.krizan@fmf.uni-lj.si', 'F428');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3193, 'Gojmir', 'Lahajnar', 'gojmir.lahajnar@fmf.uni-lj.si', 'F428');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3204, 'Boris', 'Lavriè', 'boris.lavric@fmf.uni-lj.si', 'M434');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3207, 'Peter', 'Legiša', 'peter.legisa@fmf.uni-lj.si', 'M422');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3210, 'Davorin', 'Lešnik', 'davorin.lesnik@fmf.uni-lj.si', 'MP.20');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3213, 'Andrej', 'Likar', 'andrej.likar@fmf.uni-lj.si', 'F419');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3228, 'Bojan', 'Magajna', 'bojan.magajna@fmf.uni-lj.si', 'M430');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3237, 'Norma Susana', 'Mankoè Borštnik', 'norma.mankoc@fmf.uni-lj.si', 'F105');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3249, 'George', 'Mejak', 'george.mejak@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3252, 'Tomaž', 'Mertelj', 'tomaz.mertelj@fmf.uni-lj.si', 'F409');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3258, 'Marko', 'Mikuž', 'marko.mikuz@fmf.uni-lj.si', 'F410');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3261, 'Bojan', 'Mohar', 'bojan.mohar@fmf.uni-lj.si', 'F303');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3264, 'Aleš', 'Mohoriè', 'ales.mohoric@fmf.uni-lj.si', 'F201');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3270, 'Primož', 'Moravec', 'primoz.moravec@fmf.uni-lj.si', 'M412');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3273, 'Janez', 'Mrèun', 'janez.mrcun@fmf.uni-lj.si', 'M405');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3279, 'Igor', 'Muševiè', 'igor.musevic@fmf.uni-lj.si', 'F403');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3294, 'Nika', 'Novak', 'nika.novak@fmf.uni-lj.si', 'M518');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3300, 'Matjaž', 'Omladiè', 'matjaz.omladic@fmf.uni-lj.si', 'M432, F314');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3303, 'Alen', 'Orbaniæ', 'alen.orbanic@fmf.uni-lj.si', 'M518');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3315, 'Natan', 'Osterman', 'natan.osterman at fmf.uni-lj.si', 'FP16, FP17');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3321, 'Petar', 'Pavešiæ', 'petar.pavesic@fmf.uni-lj.si', 'M408');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3336, 'Marko', 'Petkovšek', 'marko.petkovsek@fmf.uni-lj.si', 'M409');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3342, 'Tomaž', 'Pisanski', 'tomaz.pisanski@fmf.uni-lj.si', 'M517');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3351, 'Gorazd', 'Planinšiè', 'gorazd.planinsic@fmf.uni-lj.si', 'F207');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3357, 'Bor', 'Plestenjak', 'bor.plestenjak@fmf.uni-lj.si', 'M404');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3366, 'Rudolf', 'Podgornik', 'rudolf.podgornik@fmf.uni-lj.si', 'F405');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3372, 'Tomaž', 'Podobnik', 'tomaz.podobnik@fmf.uni-lj.si', 'F112');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3378, 'Dušan', 'Ponikvar', 'dusan.ponikvar@fmf.uni-lj.si', 'F002, F012');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3384, 'Primož', 'Potoènik', 'primoz.potocnik@fmf.uni-lj.si', 'MP27 (pritlièje)');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3387, 'Peter', 'Prelovšek', 'peter.prelovsek@fmf.uni-lj.si', 'F101');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3390, 'Jasna', 'Prezelj', 'jasna.prezelj@fmf.uni-lj.si', 'M510');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3393, 'Tomaž', 'Prosen', 'tomaz.prosen@fmf.uni-lj.si', 'F407');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3399, 'Martin', 'Raiè', 'martin.raic@fmf.uni-lj.si', 'M512');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3402, 'Jože', 'Rakovec', 'joze.rakovec@fmf.uni-lj.si', 'F119');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3409, 'Anton', 'Ramšak', 'anton.ramsak@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3412, 'Miha', 'Ravnik', 'miha.ravnik@fmf.uni-lj.si', 'F411');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3421, 'Mitja', 'Rosina', 'mitja.rosina@fmf.uni-lj.si', 'F422b');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3427, 'Pavle', 'Saksida', 'pavle.saksida@fmf.uni-lj.si', 'M420');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3430, 'Janez', 'Seliger', 'janez.seliger@fmf.uni-lj.si', 'F429');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3436, 'Gregor', 'Skaèej', 'gregor.skacej@fmf.uni-lj.si', 'F412');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3442, 'Gregor', 'Skok', 'gregor.skok@fmf.uni-lj.si', 'F116');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3451, 'Jaka', 'Smrekar', 'jaka.smrekar@fmf.uni-lj.si', 'M413');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3460, 'Janez', 'Stepišnik', 'janez.stepisnik@fmf.uni-lj.si', 'F404');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3463, 'Sašo', 'Strle', 'saso.strle@fmf.uni-lj.si', 'M401');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3472, 'Andreja', 'Šarlah', 'andreja.sarlah@fmf.uni-lj.si', 'F412');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3478, 'Gregor', 'Šega', 'gregor.sega@fmf.uni-lj.si', 'M512');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3481, 'Peter', 'Šemrl', 'peter.semrl@fmf.uni-lj.si', 'M410');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3487, 'Simon', 'Širca', 'simon.sirca@fmf.uni-lj.si', 'F417');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3493, 'Klemen', 'Šivic', 'klemen.sivic@fmf.uni-lj.si', 'M507');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3504, 'Riste', 'Škrekovski', 'riste.skrekovski@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3507, 'Žiga', 'Šmit', 'ziga.smit@fmf.uni-lj.si', 'F208');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3516, 'Jernej', 'Tonejc', 'jernej.tonejc@fmf.uni-lj.si', 'F312');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3519, 'Zvonko', 'Trontelj', 'zvonko.trontelj@fmf.uni-lj.si', 'F307');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3525, 'Aleš', 'Vavpetiè', 'ales.vavpetic@fmf.uni-lj.si', 'M513');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3529, 'Dejan', 'Velušèek', 'dejan.veluscek@fmf.uni-lj.si', 'M516');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3535, 'Žiga', 'Virk', 'ziga.virk@fmf.uni-lj.si', 'M518');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3544, 'Matjaž', 'Zaveršnik', 'matjaz.zaversnik@fmf.uni-lj.si', 'MP20');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3547, 'Marko', 'Zgonik', 'marko.zgonik@fmf.uni-lj.si', 'F401');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3550, 'Primož', 'Ziherl', 'primoz.ziherl@fmf.uni-lj.si', 'F204');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3559, 'Tomaž', 'Zwitter', 'tomaz.zwitter@fmf.uni-lj.si', 'F425');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3565, 'Rahela', 'Žabkar', 'rahela.zabkar@fmf.uni-lj.si', 'F118');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3571, 'Emil', 'Žagar', 'emil.zagar@fmf.uni-lj.si', 'M433');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3574, 'Nedjeljka', 'Žagar', 'nedjeljka.zagar@fmf.uni-lj.si', 'F115');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3577, 'Matjaž', 'Željko', 'matjaz.zeljko@fmf.uni-lj.si', 'M313');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3580, 'Arjana', 'Žitnik', 'arjana.zitnik@fmf.uni-lj.si', 'M504');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3583, 'Marko', 'Žnidariè', 'marko.znidaric (atat) fmf.uni-lj.si', 'F406');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (3589, 'Slobodan', 'Žumer', 'slobodan.zumer@fmf.uni-lj.si', 'F102');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (4332, 'Borut', 'Mavko', 'borut.mavko@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (4355, 'Leon', 'Cizelj', 'Leon.Cizelj@ijs.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (4802, 'Tomaž', 'Rejec', 'tomaz.rejec@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (6844, 'Damijan', 'Škrk', 'damijan.skrk@gov.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (6851, 'Iztok', 'Tiselj', 'iztok.tiselj@ijs.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (7314, 'Gregor', 'Kladnik', 'gregor.kladnik@fmf.uni-lj.si', 'F008');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (7368, 'Andreja', 'Drobniè Vidic', 'andreja.drobnic@fmf.uni-lj.si', 'F5.04');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (7384, 'Saša', 'Prelovšek Komelj', 'sasa.prelovsek@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (7477, 'Dušan', 'Repovš', 'dusan.repovs@guest.arnes.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (8763, 'Gregor', 'Bavdek', 'gregor.bavdek@fmf.uni-lj.si', 'F008');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9333, 'Benedikt', 'Strajnar', 'benedikt.strajnar@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9336, 'Miha', 'Škarabot', 'miha.skarabot@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9405, 'Dragan', 'Mihailoviæ', 'dragan.mihailovic@ijs.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9411, 'Boštjan', 'Zalar', 'bostjan.zalar@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9466, 'Marko', 'Kandiæ', 'marko.kandic@fmf.uni-lj.si', 'M513');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (9577, 'Sergej', 'Faletiè', 'sergej.faletic@fmf.uni-lj.si', 'F213');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (10778, 'Sandi', 'Klavžar', 'Sandi.Klavzar@fmf.uni-lj.si', 'F403');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (11200, 'Matej', 'Brešar', 'matej.bresar@fmf.uni-lj.si', 'M423');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (11259, 'Aleš', 'Toman', 'ales.toman@imfm.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (12718, 'Andraž', 'Briški Javor', 'andraz.briskijavor@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (14143, 'Matija', 'Pretnar', 'matija.pretnar@fmf.uni-lj.si', 'M519');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (14284, 'Janko', 'Marovt', 'janko.marovt@uni-mb.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (14351, 'Drejc', 'Kopaè', 'drejc.kopac@fmf.uni-lj.si', 'F214');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (14358, 'Nina', 'Otopal', 'nina.klenovsek@imfm.si', 'F316');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (14437, 'Mihael', 'Gojkošek', 'gojkosek@fmf.uni-lj.si', 'F204');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (15977, 'Marko', 'Razpet', 'marko.razpet@guest.arnes.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (16068, 'Jože', 'Vrabec', 'Joze.Vrabec@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (17096, 'Simon', 'Èopar', 'simon.copar@fmf.uni-lj.si', 'F410');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (17137, 'Matjaž', 'Konvalinka', 'matjaz.konvalinka@fmf.uni-lj.si', 'F414');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (18014, 'Dunja', 'Fabjan', 'dunja.fabjan@fmf.uni-lj.si', 'F423');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22297, 'Blaž', 'Jelenc', 'blaz.jelenc@fmf.uni-lj.si', 'F317');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22300, 'Matjaž', 'Krnc', 'matjaz.krnc@fmf.uni-lj.si', 'F318');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22303, 'Uroš', 'Kuzman', 'uros.kuzman@gmail.com', 'M510');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22313, 'Lucijan', 'Plevnik', 'lucijan.plevnik@fmf.uni-lj.si', 'M511');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22319, 'Špela', 'Špenko', 'spela.spenko@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22322, 'Janez', 'Šter', 'janez.ster@imfm.si', 'F317');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22325, 'Gašper', 'Zadnik', 'zadnik@fmf.uni-lj.si', 'F310');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22463, 'Tadej', 'Starèiè', 'tadej.starcic@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (22755, 'Marko', 'Boben', 'marko.boben@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (24311, 'Urban', 'Jezernik', 'urban.jezernik@fmf.uni-lj.si', 'M5.11');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (25498, 'Andrej', 'Trkov', 'andrej.trkov@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (25508, 'Boštjan', 'Konèar', 'bostjan.koncar@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (25514, 'Ivo', 'Kljenak', 'ivo.kljenak@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (25858, 'Sonja', 'Jejèiè', 'sonja.jejcic@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27090, 'Matija', 'Cencelj', 'matija.cencelj (at) pef.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27892, 'Vid', 'Podpeèan', 'vid.podpecan@ijs.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27897, 'Janoš', 'Vidali', 'janos.vidali@fmf.uni-lj.si', 'M514');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27902, 'Ugo', 'Marzolino', 'ugo.marzolino@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27909, 'Nejc', 'Košnik', 'nejc.kosnik@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (27918, 'Mihael', 'Perman', 'mihael.perman@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (29072, 'Aljaž', 'Zalar', 'Aljaz.Zalar@imfm.si', 'F317');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (29119, 'Aleksej', 'Majkiæ', 'aleksej.majkic@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (29124, 'Franci', 'Bajd', 'franci.bajd@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (31256, 'Anže', 'Zupanc', 'anze.zupanc@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (31259, 'Urban', 'Simonèiè', 'urban.simoncic@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (31614, 'Marko', 'Medenjak', 'marko.medenjak@fmf.uni-lj.si', 'F408a');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (31624, 'Matija', 'Vidmar', 'matija.vidmar@fmf.uni-lj.si', 'MP18');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (32646, 'Alex', 'Simpson', 'Alex.Simpson@fmf.uni-lj.si', 'F4.28');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (32716, 'Robert', 'Jeraj', 'robert.jeraj@fmf.uni-lj.si', 'F422');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (32872, 'Andrej', 'Studen', 'andrej.studen@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (33907, 'Matija', 'Milaniè', 'matija.milanic@fmf.uni-lj.si', 'F422');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (34634, 'Barbara', 'Ikica', 'barbara.ikica@imfm.si', 'F318');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (34639, 'Dejan', 'Govc', 'dejan.govc@imfm.si', 'F317');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (34692, 'Tilen', 'Marc', 'tilen.marc@imfm.si', 'F317');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (34783, 'Jan', 'Grošelj', 'jan.groselj@fmf.uni-lj.si', 'F515');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (34804, 'Matej', 'Praprotnik', 'matej.praprotnik@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (35101, 'Jordan', 'Stoyanov', 'jordan.stoyanov@fmf.uni-lj.si', 'FP41');
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (35201, 'Angela', 'Kochoska', 'angela.kochoska@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (38505, 'Riccardo', 'Ugolini', 'riccardo.ugolini@imfm.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (39700, 'Karla', 'Ferjanèiè', 'karla.ferjancic@fmf.uni-lj.si', NULL);
INSERT INTO ucitelji (id, ime, priimek, email, kabinet) VALUES (39731, 'Boris', 'Majaron', 'boris.majaron@fmf.uni-lj.si', NULL);

-- Table: vloge
CREATE TABLE vloge (
                id integer PRIMARY KEY,
                opis text
                );
INSERT INTO vloge (id, opis) VALUES (0, 'predavatelj');
INSERT INTO vloge (id, opis) VALUES (1, 'asistent');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
